# Import Libraries

In [116]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

# Read the Datasets

In [117]:
df_train = pd.read_csv("G:/My Drive/Data Sets/train.csv")
df_test = pd.read_csv("G:/My Drive/Data Sets/test.csv")

In [118]:
df_train.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [119]:
df_test.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001015   Male     Yes          0      Graduate            No   
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History Property_Area  
0             1.0         Urban  
1             1.0         Urban  
2             1.0         Urban  
3             NaN         Urban  
4             1.0         Urban

In [120]:
df_train.shape

(614, 13)

In [121]:
df_test.shape

(367, 12)

In [122]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [123]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            367 non-null    object 
 1   Gender             356 non-null    object 
 2   Married            367 non-null    object 
 3   Dependents         357 non-null    object 
 4   Education          367 non-null    object 
 5   Self_Employed      344 non-null    object 
 6   ApplicantIncome    367 non-null    int64  
 7   CoapplicantIncome  367 non-null    int64  
 8   LoanAmount         362 non-null    float64
 9   Loan_Amount_Term   361 non-null    float64
 10  Credit_History     338 non-null    float64
 11  Property_Area      367 non-null    object 
dtypes: float64(3), int64(2), object(7)
memory usage: 34.5+ KB


# Descriptive Analysis

In [124]:
df_train.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

# Check Missing Values

In [125]:
df_train.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [126]:
df_test.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

# Convert Missing values into Mode and mean

In [127]:
df_train["Credit_History"].fillna(df_train["Credit_History"].mode()[0], inplace =True) 
df_test["Credit_History"].fillna(df_test["Credit_History"].mode()[0], inplace =True)  

df_train["Gender"].fillna(df_train["Gender"].mode()[0], inplace =True)   
df_test["Gender"].fillna(df_test["Gender"].mode()[0], inplace =True)     

df_train["Married"].fillna(df_train["Married"].mode()[0], inplace =True)    

df_train["Dependents"].fillna(df_train["Dependents"].mode()[0], inplace =True)   
df_test["Dependents"].fillna(df_test["Dependents"].mode()[0], inplace =True)   

df_train["Loan_Amount_Term"].fillna(df_train["Loan_Amount_Term"].mode()[0], inplace =True)  
df_test["Loan_Amount_Term"].fillna(df_test["Loan_Amount_Term"].mode()[0], inplace =True)

df_train["Self_Employed"].fillna(df_train["Self_Employed"].mode()[0], inplace =True)  
df_test["Self_Employed"].fillna(df_test["Self_Employed"].mode()[0], inplace =True)


df_train["LoanAmount"].fillna(df_train["LoanAmount"].mean(), inplace = True)    
df_test["LoanAmount"].fillna(df_test["LoanAmount"].mean(), inplace = True)    

In [128]:
df_train.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [129]:
df_test.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

# Check Numerical and Categorical features 

In [130]:
numerical_features = df_train.select_dtypes(include = [np.number])
categorical_features = df_train.select_dtypes(exclude = [np.number])

print("numerical_features:" , numerical_features.shape[1])
print("categorical_features:" , categorical_features.shape[1])

numerical_features: 5
categorical_features: 8


In [131]:
categorical_features

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

    Property_Area Loan_Status  
0           Urban           Y  
1           Rural           N  
2           Urban           Y  
3           Urban           Y  
4           Urban           Y  
..            ...         ...  
609         Rural           Y  
610         Rural           Y  
611         Urban           Y  
612         Urban           Y  
613     Semiurban           N  

[614 rows x 8 columns]

# Convert categorical to Numerical features by using LabelEncoder

In [132]:
from sklearn.preprocessing import LabelEncoder
feature_col = ["Loan_ID","Gender","Married","Self_Employed","Property_Area","Education","Dependents","Loan_Status"]
le= LabelEncoder()
for col in feature_col:
    df_train[col] = le.fit_transform(df_train[col])
    

In [133]:
df_train.head(11)

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0         0       1        0           0          0              0   
1         1       1        1           1          0              0   
2         2       1        1           0          0              1   
3         3       1        1           0          1              0   
4         4       1        0           0          0              0   
5         5       1        1           2          0              1   
6         6       1        1           0          1              0   
7         7       1        1           3          0              0   
8         8       1        1           2          0              0   
9         9       1        1           1          0              0   
10       10       1        1           2          0              0   

    ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0              5849                0.0  146.412162             360.0   
1              4583             1508.0  128.000000             360.0   
2              3000                0.0   66.000000             360.0   
3              2583             2358.0  120.000000             360.0   
4              6000                0.0  141.000000             360.0   
5              5417             4196.0  267.000000             360.0   
6              2333             1516.0   95.000000             360.0   
7              3036             2504.0  158.000000             360.0   
8              4006             1526.0  168.000000             360.0   
9             12841            10968.0  349.000000             360.0   
10             3200              700.0   70.000000             360.0   

    Credit_History  Property_Area  Loan_Status  
0              1.0              2            1  
1              1.0              0            0  
2              1.0              2            1  
3              1.0              2            1  
4              1.0              2            1  
5              1.0              2            1  
6              1.0              2            1  
7              0.0              1            0  
8              1.0              2            1  
9              1.0              1            0  
10             1.0              2            1

# Drop unwanted column

In [134]:
df_train = df_train.drop(["Loan_ID"] , axis =1)

In [135]:
df_train.shape

(614, 12)

# Standarized the data

In [136]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_train = scaler.fit_transform(df_train)
df_train

array([[ 0.47234264, -1.37208932, -0.73780632, ...,  0.41173269,
         1.22329839,  0.67451931],
       [ 0.47234264,  0.72881553,  0.25346957, ...,  0.41173269,
        -1.31851281, -1.48253724],
       [ 0.47234264,  0.72881553, -0.73780632, ...,  0.41173269,
         1.22329839,  0.67451931],
       ...,
       [ 0.47234264,  0.72881553,  0.25346957, ...,  0.41173269,
         1.22329839,  0.67451931],
       [ 0.47234264,  0.72881553,  1.24474546, ...,  0.41173269,
         1.22329839,  0.67451931],
       [-2.11710719, -1.37208932, -0.73780632, ..., -2.42876026,
        -0.04760721, -1.48253724]])

# Using PCA for feature selection

In [137]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 10)
X_pca = pca.fit_transform(df_train)
df1 = pd.DataFrame(X_pca)
df1

0         1         2         3         4         5         6  \
0   -0.761690 -0.839934  0.935189  0.356105  0.729355 -0.812087 -0.051104   
1    0.326470  0.644349 -0.460217  0.096533 -1.316556 -0.193945  0.098710   
2   -0.121286 -1.039264 -0.001506 -0.648112  1.002979  0.587734 -2.627638   
3   -0.465077 -0.765639 -1.316538  0.052152  0.275130 -0.235549  0.052978   
4   -0.784140 -0.844335  0.922184  0.343357  0.737621 -0.818305 -0.055722   
..        ...       ...       ...       ...       ...       ...       ...   
609 -2.296927 -0.692479  1.437951 -0.504068 -0.598274  0.372650  0.663110   
610  0.901354 -1.019512 -2.061089 -1.060055  0.576215  0.339994  1.050119   
611  1.342888 -0.840543  0.403711  0.357665  0.527492 -1.243377 -0.220544   
612  1.274410 -0.902412 -0.203141  0.063306  0.645577 -1.405327 -0.509173   
613 -1.513527  2.884207  1.953993 -0.872250  0.972889  1.313826 -1.703571   

            7         8         9  
0   -0.578303  0.793301 -0.969633  
1   -0.476557 -0.868632 -0.073311  
2   -1.152070  0.427792  0.538301  
3    0.250934  2.055622  0.786118  
4   -0.588049  0.783583 -0.975515  
..        ...       ...       ...  
609  0.483920 -1.303433  0.221463  
610 -0.141264 -2.689400 -0.846270  
611  0.089994  0.530597  0.216860  
612  0.578543 -0.012812 -0.299436  
613  0.003219 -0.849647  0.566732  

[614 rows x 10 columns]

# Split dataset

In [ ]:
X = df_train.drop('Loan_Status' , axis = 1)
X

In [ ]:
y = df_train['Loan_Status']
y

# Perform feature selection using RFE

In [88]:
from sklearn.feature_selection import RFE

In [89]:
rfe = RFE(estimator=LogisticRegression(), n_features_to_select=10)
rfe_df = rfe.fit_transform(X ,y)
df2 = pd.DataFrame(rfe_df)
df2

C:\Users\admin\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\admin\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

0    1    2    3    4       5           6      7    8    9
0    1.0  0.0  0.0  0.0  0.0     0.0  146.412162  360.0  1.0  2.0
1    1.0  1.0  1.0  0.0  0.0  1508.0  128.000000  360.0  1.0  0.0
2    1.0  1.0  0.0  0.0  1.0     0.0   66.000000  360.0  1.0  2.0
3    1.0  1.0  0.0  1.0  0.0  2358.0  120.000000  360.0  1.0  2.0
4    1.0  0.0  0.0  0.0  0.0     0.0  141.000000  360.0  1.0  2.0
..   ...  ...  ...  ...  ...     ...         ...    ...  ...  ...
609  0.0  0.0  0.0  0.0  0.0     0.0   71.000000  360.0  1.0  0.0
610  1.0  1.0  3.0  0.0  0.0     0.0   40.000000  180.0  1.0  0.0
611  1.0  1.0  1.0  0.0  0.0   240.0  253.000000  360.0  1.0  2.0
612  1.0  1.0  2.0  0.0  0.0     0.0  187.000000  360.0  1.0  2.0
613  0.0  0.0  0.0  0.0  1.0     0.0  133.000000  360.0  0.0  1.0

[614 rows x 10 columns]

# Split the dataset into Train and Test

In [138]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df1,y , test_size = 0.25, random_state = 0)

In [139]:
print("X_train:" ,x_train.shape)
print("Y_train:" ,y_train.shape)

X_train: (460, 10)
Y_train: (460,)


In [140]:
print("X_test:" ,x_test.shape)
print("Y_test:" ,y_test.shape)

X_test: (154, 10)
Y_test: (154,)


# Logistic Regression Model make 

In [189]:
from sklearn.linear_model import LogisticRegression

In [190]:
lr = LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [191]:
y_pred1 = lr.predict(x_test)
y_pred1

array([1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0])

# calculate F1_Score

In [192]:
from sklearn.metrics import f1_score


f1_score1 = f1_score(y_test, y_pred1)
print('f1_score :', f1_score1)

f1_score : 0.9909090909090909


# Calculate Confusion Matrix and Accuracy of Model

In [193]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, pred)
accuracy = (43 + 109) / (43 + 109 + 0 + 2)

print('confusion_matrix_accuracy_percent : ',round(accuracy*100))
print('confusion_matrix : ', cm)

confusion_matrix_accuracy_percent :  99
confusion_matrix :  [[ 43   0]
 [  2 109]]


# Calculate Mean Absolute Error , Mean Squared Error and Root Mean Squared Error

In [232]:
from sklearn.metrics import mean_absolute_error as mae

Error1 = mae(y_test,pred)

rmse1 = np.sqrt(Error1)

print("Mean_Absolute_Error_1 Model: ", Error1)
print("Root_Mean_Squared_Error_1 Model: ", rmse1)

Mean_Absolute_Error_1 Model:  0.012987012987012988
Root_Mean_Squared_Error_1 Model:  0.11396057645963795


# Decision Tree Model

In [195]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import accuracy_score

dt = DecisionTreeRegressor()
dt.fit(x_train,y_train)

DecisionTreeRegressor()

In [196]:
y_pred2 =dt.predict(x_test) 
y_pred2

array([1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0.,
       1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1.,
       0.])

# Calculate F1_Score

In [197]:
f1_score2 = f1_score(y_test, y_pred2)
print('f1_score :', f1_score2)

f1_score : 0.9775784753363228


# Calculate Mean Absolute Error , Mean Squared Error and Root Mean Squared Error

In [233]:
Error2 = mae(y_test,y_pred2)

rmse2 = np.sqrt(Error2)

print("Mean_Absolute_Error_2 Model: ", Error2)
print("Root_Mean_Squared_Error_2 Model: ", rmse2)

Mean_Absolute_Error_2 Model:  0.032467532467532464
Root_Mean_Squared_Error_2 Model:  0.1801874925391118


# Random Forest Model

In [199]:
from sklearn.ensemble import RandomForestClassifier

In [200]:
rf = RandomForestClassifier()
rf.fit(x_train,y_train)


RandomForestClassifier()

In [201]:
y_pred3 = rf.predict(x_test)
y_pred3

array([1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0])

# Calculate F1_Score

In [204]:
f1_score3 = f1_score(y_test, y_pred3)
print('f1_score :', f1_score3)

f1_score : 0.9909090909090909


# Calculate Mean Absolute Error , Mean Squared Error and Root Mean Squared Error

In [231]:
Error3 = mae(y_test,y_pred3)

rmse3 = np.sqrt(Error3)

print("Mean_Absolute_Error_3 Model: ", Error3)
print("Root_Mean_Squared_Error_3 Model: ", rmse3)

Mean_Absolute_Error_3 Model:  0.012987012987012988
Root_Mean_Squared_Error_3 Model:  0.11396057645963795


# SVM Model

In [209]:
from sklearn.svm import SVC

svm = SVC()
svm.fit(x_train,y_train)

SVC()

In [210]:
y_pred4 = svm.predict(x_test)
y_pred4

array([1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0])

# Calculate F1_Score

In [211]:
f1_score4 = f1_score(y_test, y_pred4)
print('f1_score :', f1_score4)

f1_score : 0.9864253393665158


# Calculate Mean Absolute Error , Mean Squared Error and Root Mean Squared Error

In [234]:
Error4 = mae(y_test,y_pred4)

rmse4 = np.sqrt(Error4)

print("Mean_Absolute_Error_4 Model: ", Error4)
print("Root_Mean_Squared_Error_4 Model: ", rmse4)

Mean_Absolute_Error_4 Model:  0.01948051948051948
Root_Mean_Squared_Error_4 Model:  0.13957263155977062


# Naive Bayes Model

In [214]:
from sklearn.naive_bayes import GaussianNB

In [215]:
NB = GaussianNB()
NB.fit(x_train,y_train)

GaussianNB()

In [216]:
y_pred5 = NB.predict(x_test)
y_pred5

array([1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0])

# Calculate F1 Score

In [218]:
f1_score5 = f1_score(y_test, y_pred5)
print('f1_score :', f1_score5)

f1_score : 0.9863013698630138


# Calculate Mean Absolute Error , Mean Squared Error and Root Mean Squared Error

In [235]:
Error5 = mae(y_test,y_pred5)

rmse5 = np.sqrt(Error5)

print("Mean_Absolute_Error: ", Error5)
print("Root_Mean_Squared_Error: ", rmse5)

Mean_Absolute_Error:  0.01948051948051948
Root_Mean_Squared_Error:  0.13957263155977062


# All F1 Score Here

In [238]:
print('Logistic_f1_score 1 : ', f1_score1)
print('Decision_f1_score 2 : ', f1_score2)
print('Random_f1_score 3 : ', f1_score3)
print('SVM_f1_score 4 : ', f1_score4)
print('Naive_f1_score 5 : ', f1_score5)

Logistic_f1_score 1 :  0.9909090909090909
Decision_f1_score 2 :  0.9909090909090909
Random_f1_score 3 :  0.9909090909090909
SVM_f1_score 4 :  0.9864253393665158
Naive_f1_score 5 :  0.9863013698630138


# All MAE and RMSE Here

In [237]:
print("Logistic_Mean_Absolute_Error_1 Model: ", Error1)
print("Logistic_Root_Mean_Squared_Error_1 Model: ", rmse1)


print("Decision_Mean_Absolute_Error_2 Model: ", Error2)
print("Decision_Root_Mean_Squared_Error_2 Model: ", rmse2)


print("Random_Mean_Absolute_Error_3 Model: ", Error3)
print("Random_Root_Mean_Squared_Error_3 Model: ", rmse3)



print("SVM_Mean_Absolute_Error_4 Model: ", Error4)
print("SVM_Root_Mean_Squared_Error_4 Model: ", rmse4)



print("Naive_Mean_Absolute_Error_5 Model: ", Error5)
print("Naive_Root_Mean_Squared_Error_5 Model: ", rmse5)

Logistic_Mean_Absolute_Error_1 Model:  0.012987012987012988
Logistic_Root_Mean_Squared_Error_1 Model:  0.11396057645963795
Decision_Mean_Absolute_Error_2 Model:  0.032467532467532464
Decision_Root_Mean_Squared_Error_2 Model:  0.1801874925391118
Random_Mean_Absolute_Error_3 Model:  0.012987012987012988
Random_Root_Mean_Squared_Error_3 Model:  0.11396057645963795
SVM_Mean_Absolute_Error_4 Model:  0.01948051948051948
SVM_Root_Mean_Squared_Error_4 Model:  0.13957263155977062
Naive_Mean_Absolute_Error_5 Model:  0.01948051948051948
Naive_Root_Mean_Squared_Error_5 Model:  0.13957263155977062
